spring:
  kafka:
    bootstrap-servers: 52.79.95.72:9092
    topic: "library-events"
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap-servers: 52.79.95.72:9092